resources:
  - ../../base-apps

namePrefix: dev-
commonLabels:
  env: development

images:
  - name: devopsabbacr.azurecr.io/hello-abb
    newTag: 1.0.1

# This section overrides the empty values in your base/secret-provider.yaml
patches:
  - target:
      kind: SecretProviderClass
      name: hello-abb-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "d8cc8071-7283-4d46-ab0b-ecce0991bbbd"
  - target:
      kind: Deployment
      name: hello-abb
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/csi/volumeAttributes/secretProviderClass
        value: "dev-hello-abb-secrets"