apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "hello-abb.fullname" . }}-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.azure.keyvaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: AppGreeting
          objectType: secret
          objectAlias: APP_GREETING
  secretObjects:
    - secretName: {{ include "hello-abb.fullname" . }}-k8s-secret
      type: Opaque
      data:
        - objectName: APP_GREETING
          key: APP_MESSAGE